# Starts the SpeedTest using IRIS Community. 
#
# This is good because it doesn't require an IRIS license to run.
#
# This is bad because IRIS Community has two important limitations:
# - Max of 5 connections: So we won't be able to use a high number of threads
# - Max Database size of 10Gb: So we won't be able to let the speed test run for too long
#
# But this configuration is good for development.
version: '3.7'

services:
  htapui:
    depends_on:
      - htapmaster
    container_name: htapui
    hostname: htapui
    image: intersystemsdc/irisdemo-demo-htap:ui-version-2.8.5
    ports:
    - "10000:4200" # Where Node Will be listening

  oracle: 
    image: container-registry.oracle.com/database/free:latest
    hostname: oracle
    init: true
    container_name: oracle
    mem_limit: 4g
    cpus: 2 
    environment:
      - ORACLE_PASSWORD=oraclepass
      - ORACLE_SID=ORCLCDB  # Oracle System Identifier (you can change it if needed)
      - ORACLE_PDB=ORCLPDB1  # Oracle Pluggable Database name
    ports:
    - 1521:1521
    

  htapmaster:
    depends_on: 
    - oracle
    container_name: htapmaster
    hostname: htapmaster
    init: true
    image: intersystemsdc/irisdemo-demo-htap:master-version-2.8.5
    ports:
      - "10002:8080" # Where Springboot Will be listening
    environment:
      - MASTER_SPEEDTEST_TITLE=SpeedTest | Oracle 
      - START_CONSUMERS=true
      - INGESTION_THREADS_PER_WORKER=2
      - INGESTION_BATCH_SIZE=1000
      - INGESTION_JDBC_URL=jdbc:oracle:thin:@oracle:1521:ORCL
      - INGESTION_JDBC_USERNAME=oracleuser
      - INGESTION_JDBC_PASSWORD=oraclepass
      - CONSUMER_JDBC_URL=jdbc:oracle:thin:@oracle:1521:ORCL
      - CONSUMER_JDBC_USERNAME=oracleuser
      - CONSUMER_JDBC_PASSWORD=oraclepass
      - CONSUMER_THREADS_PER_WORKER=1
      - CONSUMER_TIME_BETWEEN_QUERIES_IN_MILLIS=0
      - DATABASE_SIZE_IN_GB=1

  ingest-worker1:
    depends_on: 
      - htapmaster
    container_name: ingest-worker1
    hostname: ingest-worker1
    init: true
    image: intersystemsdc/irisdemo-demo-htap:oracle-jdbc-ingest-worker-version-2.8.5
    ports:
      - "10003:8080" # Where Springboot Will be listening
    environment:
      - MASTER_HOSTNAME=htapmaster
      - MASTER_PORT=8080

  query-worker1:
    depends_on: 
      - htapmaster
    container_name: query-worker1
    hostname: query-worker1
    init: true
    image: intersystemsdc/irisdemo-demo-htap:oracle-jdbc-query-worker-version-2.8.5
    ports:
      - "10004:8080" # Where Springboot Will be listening
    environment:
      - MASTER_HOSTNAME=htapmaster
      - MASTER_PORT=8080
